### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by jeddy3** [stylelint/jest-preset-stylelint#19]
We should release `2.0.0`.

I don't have access to the npm package. Please can someone with access either:

- grant me access
- release the package themselves

**Comment by hudochenkov** [comment]
@ntwb help :)

**Comment by ntwb** [comment]
Oh, sorry, just looked and I only have access for some reason :(

Tried adding you both via the UI and ended up with “Internal Server” error

I’ll try adding you both via the CLI shortly

**Comment by ntwb** [comment]
This doesn't work from the cli either either 😞 

```
❯ npm owner add jeddy3 jest-preset-stylelint
This operation requires a one-time password.
Enter OTP: 002610
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/jest-preset-stylelint/-rev/5-e3a096a3a3a54692c6e3b4b9ef8c6506 - Team not found
npm ERR! 404 
npm ERR! 404  'jest-preset-stylelint@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/netweb/.npm/_logs/2020-05-08T07_33_14_400Z-debug.log
```

And I get the previous error mentioned above at https://www.npmjs.com/package/jest-preset-stylelint/access

**Comment by ntwb** [comment]
I've just published 2.0.0 https://github.com/stylelint/jest-preset-stylelint/releases/tag/2.0.0

And sorry about the access, will ensure I get this fixed ASAP

Lastly, thanks for the work here everyone, greatly appreciated 🎉

**Comment by hudochenkov** [comment]
`stylelint-order` is using this preset now. And I sent a PR to https://github.com/YozhikM/stylelint-a11y/pull/54. Wanted to updated `stylelint-scss`, but then 114 tests are failing (due to missing `message` on reject, or when test has multiple warnings).

After https://github.com/stylelint/stylelint/pull/4755 merged, I can migrate core repository to it.

**Comment by jeddy3** [comment]
> but then 114 tests are failing (due to missing message on reject, or when test has multiple warnings).

Shall we drop an issue in their tracker? Both the missing message and multiple warnings failings are something they probably want to address as they'll increase confidence in their code.

**Comment by hudochenkov** [comment]
> Shall we drop an issue in their tracker? Both the missing message and multiple warnings failings are something they probably want to address as they'll increase confidence in their code.

Done https://github.com/kristerkari/stylelint-scss/pull/470

**Comment by ntwb** [comment]
So this package is under my npm `netweb` organisation which is why I couldn’t add anyone, npm have added you @jeddy3 to this package and I think my organisation 

I’ll transfer this repo to the stylelint org later today, that should resolve this issue and we’ll be able to add all the team members correctly
