### ISSUE TITLE
Grant access to publish NPM to other maintainers

### ISSUE THREAD

**Issue by jeddy3** [stylelint/jest-preset-stylelint#23]
Waiting to hear back from NPM support.

See: https://github.com/stylelint/jest-preset-stylelint/issues/19#issuecomment-625682384

**Comment by ntwb** [comment]
Aside, npm has granted us to take over the following packages:

```
We've not heard back and wanted to follow up. We're inclined to move forward with the request concerning the @ name. Please reply back by May 8, 2020, if this is a concern.

You can also run the following commands to transfer ownership:
npm owner add ntwb stylelint-vscode
npm owner add ntwb stylelint-warning-to-vscode-diagnostic
npm owner add ntwb stylelint-processor-name-to-vscode-language-ids
```

Trying to add myself as an owner (or anyone else on the @stylelint team) also fails with an error

**Comment by ntwb** [comment]
Just because we're talking about a similar theme here in broadening and bringing the stylelint ecosystem back to a _maintained_ ecosystem

> https://github.com/davidtheclark/stylelint-selector-bem-pattern.git

We should look at bringing this repo back to the stylelint org

It was transferred to https://github.com/simonsmith/stylelint-selector-bem-pattern some time ago, but for the most part is no longer maintained as the last release was [~13 months ago](https://github.com/simonsmith/stylelint-selector-bem-pattern/releases)

I'd be happy to maintain this repo as either part of the @wordpress project, or as part of the @stylelint project so personally it doesn't matter to me which GitHub repo this is located.

cc @davidtheclark @simonsmith

**Comment by hudochenkov** [comment]
I don't think it is necessary for a plugin to be in the organization. It's not vital for stylelint itself, and it's not needed for majority of our users. Because of this I don't think we should be responsible for it.

**Comment by simonsmith** [comment]
@ntwb I'd be happy to add you as a maintainer if you like?

**Comment by ntwb** [comment]
Thanks @simonsmith, that would be great please :)

To explain the background @hudochenkov on why I suggested to more the package to the stylelint org was that if I am going to help, or even take over the package then for the most part it doesn't matter which GitHub org the package lives under, it's just a Git repo 😃

Anyways, I'll go with being a maintainer on it and see how that goes :)

**Comment by ntwb** [comment]
Ugh, replied to the wrong issue ;)

> Via https://github.com/stylelint/jest-preset-stylelint/issues/19#issuecomment-629601044
> So this package is under my npm `netweb` organisation which is why I couldn’t add anyone, npm have added you @jeddy3 to this package and I think my organisation 
>
> I’ll transfer this repo to the stylelint org later today, that should resolve this issue and we’ll be able to add all the team members correctly

I'll take a look at getting this done shortly

**Comment by ntwb** [comment]
Closing as resolved as the package is part of the npm stylelint org now
